/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayersIndexRouteImport } from './routes/players.index'
import { Route as SimMatchIdRouteImport } from './routes/sim.$matchId'
import { Route as PlayersCompareRouteImport } from './routes/players.compare'
import { Route as PlayersNameRouteImport } from './routes/players.$name'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'
import { Route as IntelMatchIdRouteImport } from './routes/intel.$matchId'
import { Route as FixtureFixtureIdRouteImport } from './routes/fixture.$fixtureId'
import { Route as CvMatchIdRouteImport } from './routes/cv.$matchId'
import { Route as CoachMatchIdRouteImport } from './routes/coach.$matchId'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiTranslateRouteImport } from './routes/api/translate'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiPlayerIntelRouteImport } from './routes/api/player-intel'
import { Route as ApiLiveFixturesRouteImport } from './routes/api/live-fixtures'
import { Route as ApiFixtureBriefRouteImport } from './routes/api/fixture-brief'
import { Route as ApiExplainRouteImport } from './routes/api/explain'
import { Route as ApiCommentaryRouteImport } from './routes/api/commentary'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimMatchIdRoute = SimMatchIdRouteImport.update({
  id: '/sim/$matchId',
  path: '/sim/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersCompareRoute = PlayersCompareRouteImport.update({
  id: '/players/compare',
  path: '/players/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersNameRoute = PlayersNameRouteImport.update({
  id: '/players/$name',
  path: '/players/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelMatchIdRoute = IntelMatchIdRouteImport.update({
  id: '/intel/$matchId',
  path: '/intel/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const FixtureFixtureIdRoute = FixtureFixtureIdRouteImport.update({
  id: '/fixture/$fixtureId',
  path: '/fixture/$fixtureId',
  getParentRoute: () => rootRouteImport,
} as any)
const CvMatchIdRoute = CvMatchIdRouteImport.update({
  id: '/cv/$matchId',
  path: '/cv/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachMatchIdRoute = CoachMatchIdRouteImport.update({
  id: '/coach/$matchId',
  path: '/coach/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslateRoute = ApiTranslateRouteImport.update({
  id: '/api/translate',
  path: '/api/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayerIntelRoute = ApiPlayerIntelRouteImport.update({
  id: '/api/player-intel',
  path: '/api/player-intel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveFixturesRoute = ApiLiveFixturesRouteImport.update({
  id: '/api/live-fixtures',
  path: '/api/live-fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFixtureBriefRoute = ApiFixtureBriefRouteImport.update({
  id: '/api/fixture-brief',
  path: '/api/fixture-brief',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExplainRoute = ApiExplainRouteImport.update({
  id: '/api/explain',
  path: '/api/explain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentaryRoute = ApiCommentaryRouteImport.update({
  id: '/api/commentary',
  path: '/api/commentary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/history': typeof HistoryRoute
  '/api/chat': typeof ApiChatRoute
  '/api/commentary': typeof ApiCommentaryRoute
  '/api/explain': typeof ApiExplainRoute
  '/api/fixture-brief': typeof ApiFixtureBriefRoute
  '/api/live-fixtures': typeof ApiLiveFixturesRoute
  '/api/player-intel': typeof ApiPlayerIntelRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/translate': typeof ApiTranslateRoute
  '/api/tts': typeof ApiTtsRoute
  '/coach/$matchId': typeof CoachMatchIdRoute
  '/cv/$matchId': typeof CvMatchIdRoute
  '/fixture/$fixtureId': typeof FixtureFixtureIdRoute
  '/intel/$matchId': typeof IntelMatchIdRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/players/$name': typeof PlayersNameRoute
  '/players/compare': typeof PlayersCompareRoute
  '/sim/$matchId': typeof SimMatchIdRoute
  '/players/': typeof PlayersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/history': typeof HistoryRoute
  '/api/chat': typeof ApiChatRoute
  '/api/commentary': typeof ApiCommentaryRoute
  '/api/explain': typeof ApiExplainRoute
  '/api/fixture-brief': typeof ApiFixtureBriefRoute
  '/api/live-fixtures': typeof ApiLiveFixturesRoute
  '/api/player-intel': typeof ApiPlayerIntelRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/translate': typeof ApiTranslateRoute
  '/api/tts': typeof ApiTtsRoute
  '/coach/$matchId': typeof CoachMatchIdRoute
  '/cv/$matchId': typeof CvMatchIdRoute
  '/fixture/$fixtureId': typeof FixtureFixtureIdRoute
  '/intel/$matchId': typeof IntelMatchIdRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/players/$name': typeof PlayersNameRoute
  '/players/compare': typeof PlayersCompareRoute
  '/sim/$matchId': typeof SimMatchIdRoute
  '/players': typeof PlayersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/history': typeof HistoryRoute
  '/api/chat': typeof ApiChatRoute
  '/api/commentary': typeof ApiCommentaryRoute
  '/api/explain': typeof ApiExplainRoute
  '/api/fixture-brief': typeof ApiFixtureBriefRoute
  '/api/live-fixtures': typeof ApiLiveFixturesRoute
  '/api/player-intel': typeof ApiPlayerIntelRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/translate': typeof ApiTranslateRoute
  '/api/tts': typeof ApiTtsRoute
  '/coach/$matchId': typeof CoachMatchIdRoute
  '/cv/$matchId': typeof CvMatchIdRoute
  '/fixture/$fixtureId': typeof FixtureFixtureIdRoute
  '/intel/$matchId': typeof IntelMatchIdRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/players/$name': typeof PlayersNameRoute
  '/players/compare': typeof PlayersCompareRoute
  '/sim/$matchId': typeof SimMatchIdRoute
  '/players/': typeof PlayersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/history'
    | '/api/chat'
    | '/api/commentary'
    | '/api/explain'
    | '/api/fixture-brief'
    | '/api/live-fixtures'
    | '/api/player-intel'
    | '/api/transcribe'
    | '/api/translate'
    | '/api/tts'
    | '/coach/$matchId'
    | '/cv/$matchId'
    | '/fixture/$fixtureId'
    | '/intel/$matchId'
    | '/match/$matchId'
    | '/players/$name'
    | '/players/compare'
    | '/sim/$matchId'
    | '/players/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/history'
    | '/api/chat'
    | '/api/commentary'
    | '/api/explain'
    | '/api/fixture-brief'
    | '/api/live-fixtures'
    | '/api/player-intel'
    | '/api/transcribe'
    | '/api/translate'
    | '/api/tts'
    | '/coach/$matchId'
    | '/cv/$matchId'
    | '/fixture/$fixtureId'
    | '/intel/$matchId'
    | '/match/$matchId'
    | '/players/$name'
    | '/players/compare'
    | '/sim/$matchId'
    | '/players'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/history'
    | '/api/chat'
    | '/api/commentary'
    | '/api/explain'
    | '/api/fixture-brief'
    | '/api/live-fixtures'
    | '/api/player-intel'
    | '/api/transcribe'
    | '/api/translate'
    | '/api/tts'
    | '/coach/$matchId'
    | '/cv/$matchId'
    | '/fixture/$fixtureId'
    | '/intel/$matchId'
    | '/match/$matchId'
    | '/players/$name'
    | '/players/compare'
    | '/sim/$matchId'
    | '/players/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  HistoryRoute: typeof HistoryRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCommentaryRoute: typeof ApiCommentaryRoute
  ApiExplainRoute: typeof ApiExplainRoute
  ApiFixtureBriefRoute: typeof ApiFixtureBriefRoute
  ApiLiveFixturesRoute: typeof ApiLiveFixturesRoute
  ApiPlayerIntelRoute: typeof ApiPlayerIntelRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiTranslateRoute: typeof ApiTranslateRoute
  ApiTtsRoute: typeof ApiTtsRoute
  CoachMatchIdRoute: typeof CoachMatchIdRoute
  CvMatchIdRoute: typeof CvMatchIdRoute
  FixtureFixtureIdRoute: typeof FixtureFixtureIdRoute
  IntelMatchIdRoute: typeof IntelMatchIdRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
  PlayersNameRoute: typeof PlayersNameRoute
  PlayersCompareRoute: typeof PlayersCompareRoute
  SimMatchIdRoute: typeof SimMatchIdRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sim/$matchId': {
      id: '/sim/$matchId'
      path: '/sim/$matchId'
      fullPath: '/sim/$matchId'
      preLoaderRoute: typeof SimMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/compare': {
      id: '/players/compare'
      path: '/players/compare'
      fullPath: '/players/compare'
      preLoaderRoute: typeof PlayersCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$name': {
      id: '/players/$name'
      path: '/players/$name'
      fullPath: '/players/$name'
      preLoaderRoute: typeof PlayersNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel/$matchId': {
      id: '/intel/$matchId'
      path: '/intel/$matchId'
      fullPath: '/intel/$matchId'
      preLoaderRoute: typeof IntelMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixture/$fixtureId': {
      id: '/fixture/$fixtureId'
      path: '/fixture/$fixtureId'
      fullPath: '/fixture/$fixtureId'
      preLoaderRoute: typeof FixtureFixtureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv/$matchId': {
      id: '/cv/$matchId'
      path: '/cv/$matchId'
      fullPath: '/cv/$matchId'
      preLoaderRoute: typeof CvMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/$matchId': {
      id: '/coach/$matchId'
      path: '/coach/$matchId'
      fullPath: '/coach/$matchId'
      preLoaderRoute: typeof CoachMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translate': {
      id: '/api/translate'
      path: '/api/translate'
      fullPath: '/api/translate'
      preLoaderRoute: typeof ApiTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/player-intel': {
      id: '/api/player-intel'
      path: '/api/player-intel'
      fullPath: '/api/player-intel'
      preLoaderRoute: typeof ApiPlayerIntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live-fixtures': {
      id: '/api/live-fixtures'
      path: '/api/live-fixtures'
      fullPath: '/api/live-fixtures'
      preLoaderRoute: typeof ApiLiveFixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fixture-brief': {
      id: '/api/fixture-brief'
      path: '/api/fixture-brief'
      fullPath: '/api/fixture-brief'
      preLoaderRoute: typeof ApiFixtureBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/explain': {
      id: '/api/explain'
      path: '/api/explain'
      fullPath: '/api/explain'
      preLoaderRoute: typeof ApiExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/commentary': {
      id: '/api/commentary'
      path: '/api/commentary'
      fullPath: '/api/commentary'
      preLoaderRoute: typeof ApiCommentaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  HistoryRoute: HistoryRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCommentaryRoute: ApiCommentaryRoute,
  ApiExplainRoute: ApiExplainRoute,
  ApiFixtureBriefRoute: ApiFixtureBriefRoute,
  ApiLiveFixturesRoute: ApiLiveFixturesRoute,
  ApiPlayerIntelRoute: ApiPlayerIntelRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiTranslateRoute: ApiTranslateRoute,
  ApiTtsRoute: ApiTtsRoute,
  CoachMatchIdRoute: CoachMatchIdRoute,
  CvMatchIdRoute: CvMatchIdRoute,
  FixtureFixtureIdRoute: FixtureFixtureIdRoute,
  IntelMatchIdRoute: IntelMatchIdRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
  PlayersNameRoute: PlayersNameRoute,
  PlayersCompareRoute: PlayersCompareRoute,
  SimMatchIdRoute: SimMatchIdRoute,
  PlayersIndexRoute: PlayersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
